/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mercado.view.DialogPesquisa;

import com.mycompany.mercado.view.DialogCad.DialogCadProduto;
import com.mycompany.mercado.dao.FornecedorDAO;
import com.mycompany.mercado.doumain.Fornecedor;
import com.mycompany.mercado.view.ViewMenu;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author walhe
 */
public class DialogPesquisarFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form DialogPesquisarFornecedor
     */
    public DialogPesquisarFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarjTableFornecedor();
    }
    //VARIAVEIS
    public Fornecedor fornecedor;
    public DialogCadProduto dialogCadProduto;
    private static DialogPesquisarFornecedor pesquisaFornecedor;
    
    
    //METODOS
    public static DialogPesquisarFornecedor getInstance(){
        if(pesquisaFornecedor == null){
            pesquisaFornecedor = new DialogPesquisarFornecedor(new javax.swing.JFrame(), true);
        }
        return pesquisaFornecedor;
    }
    public void carregarjTableFornecedor() {
        List<Fornecedor> fornecedores = FornecedorDAO.getInstance().findAll();
        DefaultTableModel model = (DefaultTableModel) jTableFornecedor.getModel();
        model.setNumRows(0);
        //Inserir Fornecedores
        for (Fornecedor f : fornecedores) {
            model.addRow(new Object[]{
                f.getId_pessoa(),
                f.getNome(),
                f.getRazaoSociao(),
                f.getCnpj(),
                f.getEmail(),
                f.getFantasia()
            });
        }
    }
    public void alterarTable(){
        if(jTableFornecedor.getSelectedRow() != -1){
            Integer codigo = (Integer) jTableFornecedor.getValueAt(jTableFornecedor.getSelectedRow(), 0);
            fornecedor = FornecedorDAO.getInstance().getById(codigo);
            forncSelecionado.setText(fornecedor.toString());
            dialogCadProduto = DialogCadProduto.getInstance();
            dialogCadProduto.retornaPesquisa(fornecedor);
            
            dialogCadProduto.setVisible(true);
        }
    }
    public void novoFornecedor(){
        ViewMenu.getInstance().dialogCadFornecedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFornecedor = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        forncSelecionado = new javax.swing.JLabel();
        botaoNovoFornecedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(87, 141, 204));

        jTableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Razão Social", "Cnpj", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFornecedor);
        if (jTableFornecedor.getColumnModel().getColumnCount() > 0) {
            jTableFornecedor.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableFornecedor.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableFornecedor.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTableFornecedor.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTableFornecedor.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        jLabel10.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel10.setText("Fornecedor:");

        forncSelecionado.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        forncSelecionado.setText("Selecione na tabela abaixo:");

        botaoNovoFornecedor.setFont(new java.awt.Font("Wide Latin", 0, 13)); // NOI18N
        botaoNovoFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/mercado/imagens/add.png"))); // NOI18N
        botaoNovoFornecedor.setText("Fornecedor");
        botaoNovoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forncSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoNovoFornecedor)
                        .addGap(76, 76, 76)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(forncSelecionado)
                    .addComponent(botaoNovoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFornecedorMouseClicked
       alterarTable();
    }//GEN-LAST:event_jTableFornecedorMouseClicked

    private void botaoNovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoFornecedorActionPerformed
        novoFornecedor();

    }//GEN-LAST:event_botaoNovoFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogPesquisarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogPesquisarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogPesquisarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogPesquisarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // DialogPesquisarFornecedor dialog = new DialogPesquisarFornecedor(new javax.swing.JFrame(), true);
                getInstance().addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoNovoFornecedor;
    private javax.swing.JLabel forncSelecionado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFornecedor;
    // End of variables declaration//GEN-END:variables
}
